# Generated by Django 3.1.5 on 2021-01-31 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classified',
            name='date',
        ),
    ]
