# Generated by Django 3.1.5 on 2021-01-31 16:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classified', '0002_remove_classified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='classified',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
